CREATE TABLE [dbo].[Vehiculo] (
    [Codigo]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [Placa]                NVARCHAR (15)  NOT NULL,
    [Marca]                NVARCHAR (50)  NOT NULL,
    [Linea]                NVARCHAR (50)  NOT NULL,
    [Modelo]               NUMERIC (4)    NOT NULL,
    [CodigoPropietario]    BIGINT         NULL,
    [CodigoAdministrador]  BIGINT         NULL,
    [CodigoConductor]      BIGINT         NULL,
    [CodigoDesignacion]    INT            NOT NULL,
    [PlacaRemolque]        NVARCHAR (15)  NULL,
    [MarcaRemolque]        NVARCHAR (50)  NULL,
    [LineaCarroceria]      NVARCHAR (50)  NULL,
    [ModeloCarroceria]     NVARCHAR (50)  NULL,
    [CodigoTipoCarroceria] INT            NOT NULL,
    [CodigoTipoCarga]      INT            NOT NULL,
    [CapacidadCarga]       DECIMAL (5, 2) NOT NULL,
    [CapacidadVolumetrica] DECIMAL (5, 2) NOT NULL,
    [Largo]                DECIMAL (5, 2) NOT NULL,
    [Ancho]                DECIMAL (5, 2) NOT NULL,
    [Alto]                 DECIMAL (5, 2) NOT NULL,
    CONSTRAINT [PK_Vehiculo_1] PRIMARY KEY CLUSTERED ([Codigo] ASC),
    CONSTRAINT [FK_Vehiculo_Administrador] FOREIGN KEY ([CodigoAdministrador]) REFERENCES [dbo].[Persona] ([Codigo]),
    CONSTRAINT [FK_Vehiculo_Conductor] FOREIGN KEY ([CodigoConductor]) REFERENCES [dbo].[Conductor] ([Codigo]),
    CONSTRAINT [FK_Vehiculo_Designacion] FOREIGN KEY ([CodigoDesignacion]) REFERENCES [dbo].[Designacion] ([Codigo]),
    CONSTRAINT [FK_Vehiculo_TipoCarga] FOREIGN KEY ([CodigoTipoCarga]) REFERENCES [dbo].[TipoCarga] ([Codigo]),
    CONSTRAINT [FK_Vehiculo_TipoCarroceria] FOREIGN KEY ([CodigoTipoCarroceria]) REFERENCES [dbo].[TipoCarroceria] ([Codigo]),
    CONSTRAINT [FK_Vehiculo_Usuario] FOREIGN KEY ([CodigoPropietario]) REFERENCES [dbo].[Persona] ([Codigo]),
    CONSTRAINT [IX_Vehiculo] UNIQUE NONCLUSTERED ([Placa] ASC)
);

